name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install pre-stow dependencies
        run: brew bundle --file=Brewfile

      - name: Run install script
        run: bash bin/install.sh

      - name: Run tests
        run: |
          bash tests/test_installation.sh
          bash tests/test_symlinks.sh
